CREATE DATABASE IF NOT EXISTS wemixt;
USE wemixt;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fullName VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  profileImage VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS members (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fullName VARCHAR(225),
  email VARCHAR(225),
  phoneNumber VARCHAR(12),
  address TEXT,
  dateOfBirth DATE,
  gender VARCHAR(10),
  bio TEXT,
  user_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    documentPath VARCHAR(255) NOT NULL,
    documentName VARCHAR(255) DEFAULT NULL,
    userId INT DEFAULT NULL,
    memberId INT DEFAULT NULL,
    uploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_documents_users FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_documents_members FOREIGN KEY (memberId) REFERENCES members(id) ON DELETE CASCADE ON UPDATE CASCADE
);
